### ISSUE TITLE
Similar project: pylint-ignore

### ISSUE THREAD

**Issue by mbarkhau** [sneakypete81/pylint-patcher#2]
I recently published a project which is very similar to yours. I think people who would consider using `pylint-patcher` might consider using `pylint-ignore` instead (not least because it supports python 3).

https://pypi.org/project/pylint-ignore/
https://gitlab.com/mbarkhau/pylint-ignore

**Comment by sneakypete81** [comment]
Thanks! I've added a link from the README.
